debugging the deployment and the smoke tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -364,26 +364,26 @@ jobs:
                     else
                         exit 1
                     fi
-            # - run:
-            #     name: Frontend smoke test.
-            #     command: |
-            #         URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
-            #         echo ${URL} 
-            #         if curl -s ${URL} | grep "Welcome"
-            #         then
-            #             # Change this to 0 after the job fails
-            #             echo "This should be a success"
-            #             exit 1
-            #         else
-            #             exit 1
-            #         fi
-            #     when: on_fail
+            - run:
+                name: Frontend smoke test.
+                command: |
+                    URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+                    echo ${URL} 
+                    if curl -s ${URL} | grep "Welcome"
+                    then
+                        # Change this to 0 after the job fails
+                        echo "This should be a success"
+                        exit 1
+                    else
+                        exit 1
+                    fi
+                when: on_fail
 
             # Here's where you will add some code to rollback on failure
-            # - empty-s3:
-            #     workflowID: "${CIRCLE_WORKFLOW_ID:0:7}"
-            # - destroy-environment:
-            #     workflowID: "${CIRCLE_WORKFLOW_ID:0:7}"
+            - empty-s3:
+                workflowID: "${CIRCLE_WORKFLOW_ID:0:7}"
+            - destroy-environment:
+                workflowID: "${CIRCLE_WORKFLOW_ID:0:7}"
 
 #     cloudfront-update:
 #         docker:
