debugging the smoke tests

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -355,20 +355,20 @@ jobs:
                     else
                         exit 1
                     fi
-            - run:
-                name: Frontend smoke test.
-                command: |
-                    URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
-                    echo ${URL} 
-                    if curl -s ${URL} | grep "Welcome"
-                    then
-                        # Change this to 0 after the job fails
-                        echo "This should be a success"
-                        exit 1
-                    else
-                        exit 1
-                    fi
-                when: on_fail
+            # - run:
+            #     name: Frontend smoke test.
+            #     command: |
+            #         URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website-us-east-1.amazonaws.com/#/employees"            
+            #         echo ${URL} 
+            #         if curl -s ${URL} | grep "Welcome"
+            #         then
+            #             # Change this to 0 after the job fails
+            #             echo "This should be a success"
+            #             exit 1
+            #         else
+            #             exit 1
+            #         fi
+            #     when: on_fail
 
             # Here's where you will add some code to rollback on failure
             # - empty-s3:
@@ -413,37 +413,39 @@ jobs:
 workflows:
     default:
         jobs:
-            - build-frontend
-            - build-backend
-            # - test-frontend:
-            #     requires: [build-frontend]
-            # - test-backend:
-            #     requires: [build-backend]
-            # - scan-frontend:
-            #     requires: [build-frontend]
-            # - scan-backend:
-            #     requires: [build-backend]
-            - deploy-infrastructure:
-                requires:
-                    [build-frontend, build-backend]
+            # - build-frontend
+            # - build-backend
+            # # - test-frontend:
+            # #     requires: [build-frontend]
+            # # - test-backend:
+            # #     requires: [build-backend]
+            # # - scan-frontend:
+            # #     requires: [build-frontend]
+            # # - scan-backend:
+            # #     requires: [build-backend]
+            # - deploy-infrastructure:
+            #     requires:
+            #         [build-frontend, build-backend]
 
-                # requires:
-                #     [test-frontend, test-backend, scan-frontend, scan-backend]
-                # filters:
-                #     branches:
-                #         only: [test-feature-branch]
+            #     # requires:
+            #     #     [test-frontend, test-backend, scan-frontend, scan-backend]
+            #     # filters:
+            #     #     branches:
+            #     #         only: [test-feature-branch]
 
-            - configure-infrastructure:
-                requires: [deploy-infrastructure]
-            - run-migrations:
-                requires: [configure-infrastructure]
-            - deploy-frontend:
-                  requires: [run-migrations]
-            - deploy-backend:
-                  requires: [run-migrations]
-            - smoke-test:
-                  requires: [deploy-backend, deploy-frontend]
+            # - configure-infrastructure:
+            #     requires: [deploy-infrastructure]
+            # - run-migrations:
+            #     requires: [configure-infrastructure]
+            # - deploy-frontend:
+            #       requires: [run-migrations]
+            # - deploy-backend:
+            #       requires: [run-migrations]
+            # - smoke-test:
+            #       requires: [deploy-backend, deploy-frontend]
             # - cloudfront-update:
             #       requires: [smoke-test]
             # - cleanup:
             #       requires: [cloudfront-update]
+
+            - smoke-test
